name: build

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Octo Organization
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"
      - name: Get Lists build
        run: |
          find . -name "*.java" -exec sh -c '
          rc=0
          for file: do
            javac -d ./bin -sourcepath ./src "$file" || rc=$?
          done
          exit $rc
          ' sh {} \;
