name: build

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "-a -i"

      - name: run eclint
        run: npx eclint fix .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "FORMAT!!!"

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"
      - name: Get Lists build
        run: sh .github/scripts/java-build.sh
